workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-32
  replicaCount: 1
  diskSpec:
      bootDiskType: pd-ssd
      bootDiskSizeGb: 100
  containerSpec:
    imageUri: gcr.io/qwiklabs-gcp-02-fcfb9e5d927d/moso:cok
